accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('signup_success/',views.SignUpSuccessView.as_view(),name='signup_success'),
    path('login/',auth_view.LoginView.as_view(template_name = 'login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(template_name = 'logout.html'),name='logout'),
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

koukaapp/urls.py
from django.urls import path
from . import views

app_name = 'koukaapp'

urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('post/',views.CreatePhotoView.as_view(),name='post'),
    path('post_done/',views.PostSuccessView.as_view(),name='post_done'),
    path('diary/<int:category>',views.CategoryView.as_view(),name='diary_cat'),
    path('user-list/<int:user>',views.UserView.as_view(),name='user_list'),
    path('blog-detail/<int:pk>/',views.BlogDetail.as_view(),name='detail'),
    path('about/',views.aboutView.as_view(),name='about'),
    path('mypage/',views.MypageView.as_view(),name='mypage'),
    path('diary/<int:pk>/delete',views.DiaryDeleteView.as_view(),name='diary_delete'),
    path('contact/',views.ContactView.as_view(),name= 'contact'),
]

koukaproject/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('koukaapp.urls')),
    path('',include('accounts.urls')),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name = "password_reset.html"),name = 'password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name = "password_reset_sent.html"),name = 'password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name = "password_reset_form.html"),name = 'password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"),name = 'password_reset_complete'),

]

koukaapp/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.
class Category(models.Model):
    title = models.CharField(
        verbose_name='武器種・カテゴリ',
        max_length=20
    )

    def __str__(self):
        return self.title
    
class Monster(models.Model):
    title = models.CharField(
        verbose_name='モンスター',
        max_length=20
    )

    def __str__(self):
        return self.title    

class ArimsPost(models.Model):
    user=models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー名',
        on_delete=models.CASCADE
    )
    
    monster_name=models.ForeignKey(
        Monster,
        verbose_name='モンスター',
        on_delete=models.PROTECT
    )


    category = models.ForeignKey(
        Category,
        verbose_name='武器種・カテゴリ',
        on_delete = models.PROTECT
    )

    title = models.CharField(
        verbose_name='タイトル',
        max_length=200
    )

    comment = models.TextField(
        verbose_name='コメント',
    )

    image1 = models.ImageField(
        verbose_name='イメージ１',
        upload_to='photos',
    )

    image2 = models.ImageField(
        verbose_name='イメージ2',
        upload_to='photos',
        blank=True,
        null=True
    )

    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add='True',
    )

    def __str__(self):
        return self.title
    

koukaapp/forms.py
from django.forms import ModelForm
from django import forms

from .models import ArimsPost

class AirmPostForm(ModelForm):

    class Meta:
        model=ArimsPost
        fields=['monster_name','category','title','comment','image1','image2',]

class ContactForm(forms.Form):

    # フィールド(変数宣言)を定義している
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # placeholderは入力場所に記載されている薄いグレーの文字
        # 17行～19行の3行でhtmlには下記の内容が記載される。
        # <input type="text" name="name"
        #         placeholder="お名前を入力して下さい"
        #         class="form-control"
        #         required id="id_name">
        self.fields['name'].widget.attrs['placeholder']  = \
            'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'

        self.fields['email'].widget.attrs['placeholder']  = \
            'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'

        self.fields['title'].widget.attrs['placeholder']  = \
            'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'

        self.fields['message'].widget.attrs['placeholder']  = \
            'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'

koukaapp/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import TemplateView,ListView
from django.views.generic import CreateView,FormView
from django.urls import reverse_lazy
from .forms import AirmPostForm , ContactForm
from django.contrib import messages
from django.core.mail import EmailMessage
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import ArimsPost
from django.views.generic import DetailView
from django.views.generic import DeleteView
# Create your views here.

class IndexView(ListView):
    template_name = 'index.html'
    context_object_name ='orderby_records'
    queryset = ArimsPost.objects.order_by('-posted_at')
    paginate_by = 6

class BlogDetail(DetailView):
    template_name='detail.html'
    model = ArimsPost

class aboutView(TemplateView):
    template_name = 'about.html'

@method_decorator(login_required,name='dispatch')
class CreatePhotoView(CreateView):
    form_class=AirmPostForm
    template_name="post.html"
    success_url= reverse_lazy('koukaapp:post_done')

    def form_valid(self,form):
        postdata=form.save(commit=False)
        postdata.user=self.request.user
        postdata.save()
        return super().form_valid(form)
    
class CategoryView(ListView):
    template_name='index.html'
    paginate_by=9
    def get_queryset(self):
        category_id =self.kwargs['category']
        categories=ArimsPost.objects.filter(
            category=category_id
        ).order_by('-posted_at')
        return categories
    
class UserView(ListView):
    template_name = 'index.html'
    paginate_by = 9
    def get_queryset(self):
        user_id =self.kwargs['user']
        user_list = ArimsPost.objects.filter(
            user=user_id).order_by('-posted_at')
        return user_list
    

class PostSuccessView(TemplateView):
    template_name='post_success.html'

class MypageView(ListView):
    template_name = 'mypage.html'
    paginate_by = 9

    def get_queryset(self):
        queryset = ArimsPost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        return queryset

class DiaryDeleteView(DeleteView):
    # 操作の対象はPhotoPostモデル
    model = ArimsPost
    # photo_delete.htmlをレンダリングする
    template_name = 'diary_delete.html'
    # 処理完了後にマイページにリダイレクト
    success_url = reverse_lazy('koukaapp:mypage')
    
    # レコードの削除を行う
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)
    
class ContactView(FormView):
    template_name = 'contact.html'

    # forms.pyのclass名
    form_class = ContactForm

    # メールを送って問題なければ、このURLにリダイレクトされる。
    success_url = reverse_lazy('koukaapp:contact')

    # フォームのバリエーションに問題がなかったら
    # （エラーがなかったら）実行されるメソッド
    def form_valid(self, form):

        # お問い合わせで入力された値を取得して代入している。
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']

        # ここでメールの内容を作成している
        subject = 'お問い合わせ: {}'.format(title)
        message = \
            '送信者名: {0}\nメールアドレス:{1}\n タイトル:{2}\n メッセージ:\n{3}' \
            .format(name, email, title, message)
        
        # 差出人
        from_email = 'ngn2349508@stu.o-hara.ac.jp'
        # 宛先
        # （配列になっているのは、宛先は複数人いる場合もあるから）
        to_list = ['ngn2349508@stu.o-hara.ac.jp']

        # messageという変数にメール内容をまとめている
        # （subject:件名、body:本文、from_email:メールを送信した人、to:宛先）
        message = EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=to_list,
                               )
        
        # メールを送るメソッド
        message.send()
        # リダイレクトされたhtmlにデータが送られる
        messages.success(
            self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)
    

koukaapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>討伐日記</title>
    <link rel="icon" type="image/x-icon" href={% static "assets/favicon.ico" %} />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href={% static "css/styles.css" %} rel="stylesheet" />
    <link href={% static "css/mystyles.css" %} rel="stylesheet" />
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand fonfon" href={% url "koukaapp:index" %}>討伐日記 - HOME</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto fonfon">
                    {% if user.is_authenticated %}  
                    <li class="nav-item"><a class="nav-link" href={% url 'koukaapp:mypage' %} class="text-white">マイページ</a></li>
                    <li class="nav-item"><a class="nav-link" href={% url 'accounts:logout' %} class="text-white">ログアウト</a></li>
                    <li class="nav-item"><a class="nav-link" href={% url 'password_reset' %} class="text-white">パスワードのリセット</a></li>
                    <li class="nav-item"><a class="nav-link" href={% url 'koukaapp:post' %}>投稿する</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href={% url "koukaapp:index" %}>Home</a></li>                    
                    <li class="nav-item"><a class="nav-link" href={% url 'accounts:signup' %}>サインアップ</a></li>
                    <li class="nav-item"><a class="nav-link" href={% url 'accounts:login' %} class="text-white">ログイン</a></li>

                    {% endif %} 
                </ul>
            </div>
        </div>
    </nav>
    <header class="masthead">
        <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
            <div class="d-flex justify-content-center">
                <div class="text-center">
                    <h1 class="mx-auto my-0 text-uppercase ">
                    <div class="fonfon">{% block title %}{% endblock %}</div></h1>
                    <a class="btn btn-primary fonfon" href={% url "koukaapp:contact" %}>contact</a>
                </div>
            </div>
        </div>
    </header>
        <!-- Masthead-->
        {% block contents %}{% endblock %}

        <center>
        <section class="contact-section bg-black">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="social d-flex justify-content-center">
                        <a class="mx-2" href="https://twitter.com"><i class="fab fa-twitter"></i></a>
                        <a class="mx-2" href="https://facebook.com/"><i class="fab fa-facebook-f"></i></a>
                        <a class="mx-2" href="https://startbootstrap.com/theme/grayscale#google_vignette"><i class="fab fa-github"></i></a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; Your Website 2023</div></footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        </center>
    </body>
</html>

koukaapp/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}contact{% endblock %}

{% block contents %}
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <strong>連絡を取りたいですか？
                        以下のフォームに記入してメッセージを送信してください。
                        できるだけ早くご連絡します。
                </strong>

                <!-- メールへ送信が成功した時にmessagesに値が入る -->
                <!-- view.pyのmessages.successメソッドに書いた内容 -->
                {% if messages %}
                <ul class = 'list-unstyled' style="list-style: none;">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{message.tags}}" {% endif %}>
                        {{ message }}
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}

                <div class="'my-5">
                    <form method="post">
                        <!-- CSRF(クロスサイトリクエストフォージェリ)対策用タグ -->
                        <!-- formタグの中に書かないと403エラーを返す -->
                        {% csrf_token %}

                        <!-- このfor文でform_class(views.py)に記載してあるformクラスの
                            フィールドの値を取り出して表示している -->
                        {% for field in form %}
                            <div class="form-floating">
                                <div class="form-group floating-label-form-group controls">
                                    <!-- ラベルタグを作成
                                        (ラベルタグを生成することで入力値の上にある文字を
                                        クリックしたら反応してカーソルを表示してくれる) -->
                                    {{ field.label_tag}}
                                    
                                    <!-- 入力欄を作成 -->
                                    {{ field }}

                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                        {% endfor %}

                        <br>
                        <!-- 送信用のボタン -->
                        <button type="submit"
                                class="btn btn-primary"
                                id="sendMessageButton">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <hr>
</main>
{% endblock %}

koukaapp/templates/detail.html
<!-- ベーステンプレートを適用する-->

<!-- ヘッダー情報のページタイトルを設定する-->
{% extends 'base.html' %}
{% load static %}


        {% block title %} {{object.title}} {% endblock %}
        {% block contents %}

      <!-- Bootstrapのグリッドシステム-->
      <center>
      <br>
      
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる-->
          <div class="col fonfon">
            <!-- タイトル -->
            <h1>{{object.title}}</h1>
            <!-- コメント -->
            <p>{{object.comment}}</p>
            <br>
            <!-- 投稿日時 -->
            <p>{{object.posted_at}}に投稿</p>
            <!-- 1枚目の写真 -->
              <p><img src="{{ object.image1.url }}" width="60%"></img></p>
              
            <!-- 2枚目の写真が投稿されていたら表示する-->
            {% if object.image2 %}
              <p><img src="{{ object.image2.url }}" width="60%"></img></p>
            {% endif %}

            <!-- 投稿写真がログイン中のユーザーのものであれば削除ボタンを表示-->
            {% if request.user == object.user %}
            <form method="POST">
            <!-- リンク先のURL
                 photo/<Photo postsテーブルのid値>/delete/-->
            <a href="{% url 'koukaapp:diary_delete' object.pk %}"
               class="btn btn-primary my-2">削除する</a>
            {% endif %}
                        
          </div>
        </div>
      </div>
</center>
      {% endblock %}

koukaapp/templates/diary_delete.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->




      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる -->
          <div class="col offset-3">
            <form method="POST">
              <br>
              <p>削除してもいいですか?</p>
              {% csrf_token %}
              <button class="btn btn-primary my-2"
                      type="submit">削除</button>
              <a href="{% url 'koukaapp:detail' object.pk %}"
                 class="btn btn-secondary my-2">キャンセル</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

koukaapp/templates/index.html
{% extends 'base.html' %}
{% load static %}


        {% block title %} HOME {% endblock %}
        {% block contents %}


                {% include "list.html" %}
                {% include "pagination.html" %}

        {% endblock %}

koukaapp/templates/list.html
<div class="album py-5 bg-light">
    <!-- Bootstrapのグリッドシステムを適用 -->
    <div class="container">
      <!-- 行要素を配置 -->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <!-- レコードが格納されたobject_listから
             レコードを1行ずつrecordに取り出す-->
        {% for record in object_list %}
        <!-- 列要素を配置 -->
        <div class="col">
          <div class="card shadow-sm">
            <!-- svgタグをimgに変更
                 src属性を追加して1枚目のイメージのURLを設定 -->
                 
                 <img src="{{ record.image1.url }}"
                 class="bd-placeholder-img card-img-top"
                 width="100%" height="225"
                 xmlns="http://www.w3.org/2000/svg"
                 role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice"
                 focusable="false">
                 <title>Placeholder</title>
                 <rect width="100%" height="100%" fill="#55595c"/>
                 <!-- <text>～</text>を削除-->
            </img>
            <!-- タイトルとボタンを出力するブロック -->
            <div class="card-body">
              <b class="card-text fonfon " style="font-size: 150%;">
                <!-- titleフィールドを出力 -->
                {{record.title}}
              </b>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <!-- 詳細ページを表示するボタン -->
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
                          onclick="location.href='{% url 'koukaapp:detail' record.pk %}'">
                          View</button>
                  <!-- カテゴリを表示するボタン -->
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
                          onclick="location.href='{% url 'koukaapp:diary_cat' category=record.category.id %}'">
                          {{record.category.title}}</button>
                </div>
                <!-- 投稿したユーザー名を出力-->
                <a href="{% url 'koukaapp:user_list' user=record.user.id %}">
                <small class="text-muted">
                  {{record.user.username}}</small>
                </a>
              </div>
            </div>
          </div>
        <!-- 列要素ここまで -->
        </div>
        <!-- forブロック終了 -->
        {% endfor %}
      <!-- 行要素ここまで -->
      </div>
    <!-- グリッドシステムここまで -->
    </div>
  </div>

koukaapp/templates/monster.html
{% block monster %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!--  /jQuery・bootstrapライブラリ読み込み -->

<!--  独自ライブラリ読み込み -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js"></script>
<!--  /独自ライブラリ読み込み -->

</head>
<body>

<div class="m-4">
<select data-placeholder="選択してください" class="chosen" style="width:200px;">  
  <option></option>  
  <option>北海道</option>  
  <option>青森県</option>  
  <option>岩手県</option>  
  <option>宮城県</option>  
  <option>秋田県</option>  
  <option>山形県</option>  
  <option>福島県</option>  
  <option>茨城県</option>  
  <option>栃木県</option>  
  <option>群馬県</option>  
  <option>埼玉県</option>  
  <option>千葉県</option>  
  <option>東京都</option>  
  <option>神奈川県</option>  
  <option>新潟県</option>  
  <option>富山県</option>  
  <option>石川県</option>  
  <option>福井県</option>  
  <option>山梨県</option>  
  <option>長野県</option>  
  <option>岐阜県</option>  
  <option>静岡県</option>  
  <option>愛知県</option>  
  <option>三重県</option>  
  <option>滋賀県</option>  
  <option>京都府</option>  
  <option>大阪府</option>  
  <option>兵庫県</option>  
  <option>奈良県</option>  
  <option>和歌山県</option>  
  <option>鳥取県</option>  
  <option>島根県</option>  
  <option>岡山県</option>  
  <option>広島県</option>  
  <option>山口県</option>  
  <option>徳島県</option>  
  <option>香川県</option>  
  <option>愛媛県</option>  
  <option>高知県</option>  
  <option>福岡県</option>  
  <option>佐賀県</option>  
  <option>長崎県</option>  
  <option>熊本県</option>  
  <option>大分県</option>  
  <option>宮崎県</option>  
  <option>鹿児島県</option>  
  <option>沖縄県</option>  
</select>  
</div>


<!-- ############ javascript  ############ -->
<script type="text/javascript">
$(function() {  
  $(".chosen").chosen({  
      search_contains: true  ,
      no_results_text:"ありません"
  })  
});  
</script>

{% endblock %}

koukaapp/templates/mypage.html
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}Mypage{% endblock %}

      {% block contents %}
      
      <!-- タイトルテンプレートは組み込まない-->
      
      <!-- ユーザーの投稿件数を表示-->
      {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
          <h4>{{user.username}}さんのマイページ</h4>
          {% if object_list.count == 0 %}
            <p>{{user.username}}さんの投稿はありません</p>
          {% else %}
            <p>投稿<strong>{{object_list.count}}</strong>件</p>
          {% endif %}
          <a href="{% url 'koukaapp:post' %}">投稿する</a>
        </div>
        <hr>
      {% endif %}
      
      <!-- 投稿一覧テンプレートの組み込み-->
      {% include "list.html" %}
        
      <!-- ページネーションの組み込み-->
      {% include "pagination.html" %}

      {% endblock %}

koukaapp/templates/pagination.html
<!-- 左右の中央に配置 -->
<ul class="pagination" style="justify-content:center">
    <!--
    前ページを表示するアイコンとリンクの設定
    ページネーションされたPageオブジェクトをpage_objで取得
    Page.has_previous: 直前にページがある場合にTrueを返す
    -->
    {% if page_obj.has_previous %}
    <!--
    前のページが存在する場合はそのページへのリンクが設定されたアイコン[<<]を表示
    Page.previous_page_number: 直前のページ番号を返す
    -->
    <li class="page-item">
        <a class="page-link"
            href="?page={{ page_obj.previous_page_number }}"
            aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}
    <!--
    すべてのページについてページ番号のアイコンを表示
    paginator.page_range: [1, 2, 3, 4] のように1から始まるページ番号を返す
    orderby_records.paginator.page_rangeとして取得
    ブロックパラメーターnumに順次取り出される
    -->
    {% for num in page_obj.paginator.page_range %}
        <!--
        各ページのアイコンを出力
        Page.number: 引き渡されたページのページ番号を返す
        -->
        {% if page_obj.number == num %}
        <!--
        処理中のページ番号が引き渡されたページのページ番号と一致する場合は
        ページ番号のアイコン(アクティブ状態)を表示(リンクは設定しない)
        -->
        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>
        <!--
        ページ番号が引き渡されたページのページ番号と一致しない場合
        -->
        {% else %}
        <!--
        ページ番号のアイコン(アクティブ状態ではない)にリンクを設定して表示
        -->
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}
    <!--
    次ページへのリンクを示すアイコンの表示
    Page.has_next: 次のページがある場合にTrueを返す
    -->
    {% if page_obj.has_next %}
    <!--
    次ページが存在する場合はリンクを設定したアイコン［>>]を表示
    Page.next_page_number: 次のページ番号を返す
    -->
      <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.next_page_number }}"
           aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
</ul>

koukaapp/templates/post_success.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}

<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Post Success{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br><br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる -->
          <div class="col offset-2">
            <h4>投稿が完了しました!</h4>  
          </dv>
        </dv>
      </dv>
      {% endblock %}